### ISSUE TITLE
[TESTNET] panic unknown field "issue_price" in types.Params

### ISSUE THREAD

**Issue by ekhvalov** [bitsongofficial/go-bitsong#150]
Hello.
I've installed testnet node by [this](https://docs.bitsong.io/blockchain/join-the-testnet) guide, but daemon crashed with an error:
```
panic: unknown field "issue_price" in types.Params
goroutine 1 [running]:                                                                                                                         
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x26f2698?, {0xc0005c9ce0?, 0x2711900?, 0xc0000506c0?}, {0x26f4e30?, 0xc0005
cb140?})
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/codec/proto_codec.go:176 +0x45
github.com/bitsongofficial/go-bitsong/x/fantoken.AppModule.InitGenesis({{{0x2713278, 0xc000d120d0}}, {{0x26f2698, 0xc000e7ee60}, {0x2713278, 0x
c000d120d0}, {0x0, 0x0}, {0x7ff63cc2c418, 0xc0005c2f20}, ...}, ...}, ...)
        /home/bitsong/go-bitsong/x/fantoken/module.go:132 +0xa2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2705588, 0xc000052060}, {0x2711880, 0xc000649d40}, {{0x0, 0x0}, {0xc000
eee800, 0xe}, 0x0, ...}, ...}, ...)
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/types/module/module.go:320 +0x29d
github.com/bitsongofficial/go-bitsong/app.(*BitsongApp).InitChainer(_, {{0x2705588, 0xc000052060}, {0x2711880, 0xc000649d40}, {{0x0, 0x0}, {0xc
000eee800, 0xe}, 0x0, ...}, ...}, ...)
        /home/bitsong/go-bitsong/app/app.go:586 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000657860, {{0x2fdf4c4c, 0xed98b4f05, 0x0}, {0xc000eee800, 0xe}, 0xc00054c240, {0x
34c8908, 0x0, 0x0}, ...})
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0005457a0, {{0x2fdf4c4c, 0xed98b4f05, 0x0}, {0xc000eee800, 0xe}, 0
xc00054c240, {0x34c8908, 0x0, 0x0}, ...})
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0?, {{0x2fdf4c4c, 0xed98b4f05, 0x0}, {0xc000eee800, 0xe}, 0xc00054c
240, {0x34c8908, 0x0, 0x0}, ...})
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x26e7488, 0x8}}, {0xc000eee800, 0xe}, 0x1, 0x0, {{0x0,
 ...}, ...}, ...}, ...)
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0005fbfd0, {0x27120e0, 0xc0000b9c70})
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x26e7488, 0x8}}, {0xc000eee800, 0xe}, 0x1, 0x0, ...}, ...)
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00116fa40, {0x2702420, 0xc00145ad20}, 0xc000ebf8d0, {0x26edb80, 0xc000ef5f50}, 0x0?, 0x0?, 0xc
000ebfae0, {0x2706350, ...}, ...)
        /home/bitsong/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x27188b8, 0xc00121be90}, {0x0, 0x0}, {0x2709590, 0xc000fb3510}, ...},
 ...)
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00118f680?, {0x34c8908?, 0x0?, 0x0?})
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00118f680, {0x34c8908, 0x0, 0x0})
        /home/bitsong/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f18500)
        /home/bitsong/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/bitsong/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/bitsong/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0006189d8, 0x17})
        /home/bitsong/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/bitsong/go-bitsong/cmd/bitsongd/main.go:16 +0x31
```
How to fix it?

**Comment by ccamel** [comment]
AFAI, the params of the `fantoken` module in the [genesis file](https://raw.githubusercontent.com/bitsongofficial/networks/master/testnet/bigbang-test-3/genesis.json) for the `bigbang-test-3` network seem incorrect:

```yaml
    "fantoken": {
      "params": {
        "issue_price": {
          "denom": "ubtsg",
          "amount": "1000000"
        }
      },
      "tokens": [],
      "burned_coins": []
    },
```

They do not correspond to the [protobuf spec](https://github.com/bitsongofficial/go-bitsong/blob/testnet/proto/bitsong/fantoken/v1beta1/params.proto). Should be:

```yaml
    "fantoken": {
      "params": {
        "issue_fee": {
          "denom": "...",
          "amount": "..."
        },
        "mint_fee": {
          "denom": "...",
          "amount": "..."
        },
        "burn_fee": {
          "denom": "...",
          "amount": "..."
        }
      },
      "fan_tokens": [...]
    },
```

Using these settings, I was able to launch the node without panicking.

**Comment by angelorc** [comment]
thank you, this bug have been solved in the mainnet version
