### ISSUE TITLE
panic: negative coin amount

### ISSUE THREAD

**Issue by Stakecraft** [bitsongofficial/go-bitsong#255]
after upgrade to v0.20.2
i got this error:
```
Dec 30 08:26:28 cosmovisor[4186061]: 8:26AM INF No final rewards module=server
Dec 30 08:26:32 cosmovisor[4186061]: panic: negative coin amount
Dec 30 08:26:32 cosmovisor[4186061]: goroutine 15 [running]:
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/types.DecCoins.Sub(...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/types/dec_coin.go:310
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.calculateDelegationRewardsBetween({{0x3da3340, 0xc000c146c0}, {0x3dd5da0, 0xc0005bbad0}, {0x3dc0ba0, 0xc002810550}, {0x7f2afb0af260, 0xc000ec6000}, {0x3dce8e0, 0xc0011a0ea0}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/x/distribution/keeper/delegation.go:48 +0x20e
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.CalculateDelegationRewards({{0x3da3340, 0xc000c146c0}, {0x3dd5da0, 0xc0005bbad0}, {0x3dc0ba0, 0xc002810550}, {0x7f2afb0af260, 0xc000ec6000}, {0x3dce8e0, 0xc0011a0ea0}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/x/distribution/keeper/delegation.go:137 +0x3f6
Dec 30 08:26:32 cosmovisor[4186061]: github.com/bitsongofficial/go-bitsong/app/upgrades/v020.CreateV020UpgradeHandler.func1({{0x3dc0c48, 0x5709680}, {0x3dd5d30, 0xc00599de80}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, {0x59ef088, ...}, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /code/app/upgrades/v020/upgrades.go:123 +0x59a
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/x/upgrade/keeper.Keeper.ApplyUpgrade({{0xc000e39308, 0x17}, 0xc000cee780, {0x3da3340, 0xc000c14a90}, {0x3dd5da0, 0xc0005bbad0}, 0xc000cee7b0, {0x3d993c0, 0xc000300780}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/x/upgrade/keeper/keeper.go:359 +0x18c
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker(_, {{0x3dc0c48, 0x5709680}, {0x3dd5d30, 0xc00599de80}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/x/upgrade/abci.go:84 +0x993
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/x/upgrade/module.go:161
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x3dc0c48, 0x5709680}, {0x3dd5d30, 0xc00599de80}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/types/module/module.go:562 +0x175
Dec 30 08:26:32 cosmovisor[4186061]: github.com/bitsongofficial/go-bitsong/app.(*BitsongApp).BeginBlocker(...)
Dec 30 08:26:32 cosmovisor[4186061]:         /code/app/app.go:382
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00279cda0, 0x20, 0x20}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, {0x59ef088, ...}, ...}, ...})
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/baseapp/abci.go:196 +0x838
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/abci/client.(*localClient).BeginBlockSync(_, {{0xc00279cda0, 0x20, 0x20}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, {0x59ef088, ...}, ...}, ...})
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/abci/client/local_client.go:283 +0xfe
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00279cda0, 0x20, 0x20}, {{0xb, 0x0}, {0xc005c80c90, 0xa}, 0x1356740, {0x59ef088, ...}, ...}, ...})
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/proxy/app_conn.go:101 +0x195
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/state.execBlockOnProxyApp({0x3dc12d8, 0xc000cab3a0}, {0x3dd3060, 0xc005b13f50}, 0xc000300f00, {0x3dd6960, 0xc005810198}, 0x2d4287)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/state/execution.go:363 +0x4fd
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc005afe1fa, 0x6}}, {0xc005afe210, 0xa}, 0x2d4287, 0x135673f, {{0xc00c0fc420, ...}, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/state/execution.go:197 +0x18e
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc005afe1fa, 0x6}}, {0xc005afe210, 0xa}, 0x2d4287, 0x135673f, {{0xc00c0fc420, ...}, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/consensus/replay.go:527 +0x226
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc005afe1fa, 0x6}}, {0xc005afe210, 0xa}, 0x2d4287, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/consensus/replay.go:433 +0x6ce
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc001958090, {0x3dc13f0, 0x5709680}, {0x3dd9330, 0xc005a4e0e0})
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/consensus/replay.go:274 +0x398
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc005afe1fa, 0x6}}, {0xc005afe210, 0xa}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/node/node.go:449 +0x1a8
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/node.NewNodeWithContext({0x3dc13f0, 0x5709680}, 0xc000948420, {0x3dae4b0, 0xc001527e00}, 0xc000bb2a60, {0x3d9a240, 0xc005810b28}, 0xc002111d60, 0x37beac0, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/node/node.go:929 +0x59b
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cometbft/cometbft/node.NewNode(0x0?, {0x3dae4b0?, 0xc001527e00?}, 0x1356740?, {0x3d9a240?, 0xc005810b28?}, 0x1?, 0x5709680?, 0x0?, {0x3dc12d8, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cometbft/cometbft@v0.37.5/node/node.go:849 +0xa9
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3dd7b60, 0xc0019992f0}, 0x0, {0x0, 0x0}, {0x3de1fc0, ...}, ...}, ...)
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/server/start.go:372 +0x1597
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/server/start.go:153 +0x45
Dec 30 08:26:32 cosmovisor[4186061]: github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/server/start.go:617 +0x23
Dec 30 08:26:32 cosmovisor[4186061]: created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile in goroutine 1
Dec 30 08:26:32 cosmovisor[4186061]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.15/server/start.go:616 +0x23f
Dec 30 08:26:32 cosmovisor[4186040]: Error: exit status 2
```

**Comment by hard-nett** [comment]
thanks for sharing the logs, after investigating, we ran into this issue due the bug that resulting this upgrade being required still persisting. This resulted in the distribution module not recognizing that there has been a new period for patched validators, leading to incorrect calculations. 

A pr that will resolve this patch is open and will be suggested to migrate to once reviewed
