### ISSUE TITLE
bitsongcli transaction question error

### ISSUE THREAD

**Issue by Bambarello** [bitsongofficial/go-bitsong#50]
When sending transaction through bitsongcli, and instead of y/N just pressing enter - the below error

```confirm transaction before signing and broadcasting [y/N]: panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/input.GetConfirmation(0xff28e1, 0x33, 0xc0009e7090, 0xc0000f9000, 0xc0009e7018, 0x1)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190806205118-0dcf1583878e/client/input/input.go:78 +0x1d9
github.com/cosmos/cosmos-sdk/x/auth/client/utils.CompleteAndBroadcastTxCLI(0xc00093e7d0, 0x1310280, 0xc000944700, 0x2ea, 0x0, 0x30d40, 0x3ff0000000000000, 0x0, 0x7ffc1ad9a78c, 0x11, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190806205118-0dcf1583878e/x/auth/client/utils/tx.go:89 +0x995
github.com/cosmos/cosmos-sdk/x/auth/client/utils.GenerateOrBroadcastMsgs(0xc0000f48c0, 0x1316080, 0xc00086dec0, 0x0, 0x0, 0x12e28c0, 0xc000010018, 0xfbe5ce, 0x4, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190806205118-0dcf1583878e/x/auth/client/utils/tx.go:40 +0x15c
github.com/cosmos/cosmos-sdk/x/staking/client/cli.GetCmdCreateValidator.func1(0xc000887680, 0xc000986990, 0x0, 0x9, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190806205118-0dcf1583878e/x/staking/client/cli/tx.go:60 +0x23e
github.com/spf13/cobra.(*Command).execute(0xc000887680, 0xc000986900, 0x9, 0x9, 0xc000887680, 0xc000986900)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b6c80, 0x86b0c0, 0xc0000b6c80, 0xfbd5e6)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000b6c80, 0x11b56b8, 0x2, 0xc000035c60)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/libs/cli/setup.go:89 +0x3c
main.main()
        /root/go-bitsong/cmd/bitsongcli/main.go:77 +0x59d
```

**Comment by angelorc** [comment]
Hello,
please use the tag `v0.3.0-dev-6`, I will update the guide before `bitsong-testnet-3`
